theme: jekyll-theme-minimal
title: Solarflame5's site
description: I’m Solarflame5, a student who likes programming, 3D modelling and video games.\n This site is WIP.
logo: logo.png
icon: favicon.ico
